// app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import ClientProvider from "@/app/Components/ClientProvider";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="es">
            <body>
                <ClientProvider>{children}</ClientProvider>
            </body>
        </html>
    );
}
