import type { Metadata } from "next";
import "./globals.scss";
import "@/app/utils/themes/viva-dark/theme.css";
import IndexProvider from "@/app/Components/IndexProvider";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="es">
            <body>
                <IndexProvider>{children}</IndexProvider>
            </body>
        </html>
    );
}
